language: node_js
node_js:
    -  "7"
before_script:
  - npm install jasmine-node -g
script:
    - npm test
    - istanbul cover jasmine-node -x 'src/log.js' --captureExceptions test/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage