language: node_js
node_js:
  - "0.10"
before_script:
  - npm install jasmine-node -g
script: 
- istanbul cover jasmine-node --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage