language: node_js
node_js:
    -  "4.1"
addons:
  sauce_connect:
    username: "system-runtime"
    access_key:
        secure: "WRT+mKn8QC5gC5ZO8Q68HN0GH3n0iTaAxN8RaB8UM/tLwRAO+pdz/VUucELHyVZur1x6XflMS7g2/Dyn2CpC30CzMqUJx883Ehbm8d1IPcrufP9DdTI75WLKfWb+HIw2PjnSWhkNBTLS0NxvcBu60b59dJ/gyuj4c2+Uh75b0lw="
before_script:
  - npm install jasmine-node -g
script:
    - npm test
    - istanbul cover jasmine-node --captureExceptions test/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - npm build